- name: install python packages
  pip:
    name: python-consul
#    version: 0.7.0

- name: install python packages
  pip: name={{ item }}
  with_items:
    - python-etcd
    - dnspython
    - boto
    - mock
    - requests
    - six
    - kazoo
    - click
    - tzlocal
    - prettytable
    - PyYAML
    - cdiff

- name: checkout patroni
  git:
    repo: git@github.com:zalando/patroni.git
    dest: /opt/patroni
    version: '{{ patroni_version }}'
    update: yes
    force: yes

- name: create /etc/patroni
  file: state=directory dest=/etc/patroni

- name: put postgres.yml
  template: src=postgres.yml.j2 dest=/etc/patroni/postgres.yml backup=no
  notify: restart patroni

- name: put patroni.service systemd unit
  template: src=patroni.service dest=/etc/systemd/system/patroni.service backup=yes

- name: put base config
  template: src={{ pgsql_base_config }} dest=/etc/patroni/postgresql.base.conf backup=no
  when: pgsql_base_config is defined
  notify: restart patroni
