---

- name: Install pgbouncer
  yum: name={{ item }} state=latest
  with_items:
    - pgbouncer

- name: create directories
  file: state=directory owner=pgbouncer dest={{ item }}
  with_items:
    - /var/log/pgbouncer
    - /var/lib/pgbouncer

- name: put config
  template: src=postgres0.yml dest=/etc/patroni/postgres.yml backup=yes

- name: restart and enable
  service: name=patroni state=restarted enabled=yes
